using System.Collections.Generic;

namespace AuthorityCouch.Models.Import
{
    public class CorporateName
    {
        public List<string[]> Data { get; set; }
        public List<string[]> Relations { get; set; }

        public CorporateName()
        {
            Data = new List<string[]>
            {
                new string[2] {"Knights of Pythias Grand Lodge, Domain of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/4"},
                new string[2] {"Pitt County Medical Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/7"},
                new string[2] {"Halifax County Hosiery Mill", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/8"},
                new string[2] {"Marietta Manufacturing Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/9"},
                new string[2] {"Barbour Boat Works, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/10"},
                new string[2] {"Wilmington Iron Works", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/11"},
                new string[2] {"Elmhurst Garden Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/12"},
                new string[2] {"Red Oak Christian Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/13"},
                new string[2] {"Christ Episcopal Church (Elizabeth City, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/14"},
                new string[2] {"Greenville Music Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/15"},
                new string[2] {"Woman's Club of Greenville", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/16"},
                new string[2] {"George M. Johnson & Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/17"},
                new string[2] {"Belvidere Academy", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/18"},
                new string[2] {"Lawrence-Gulley General Store", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/19"},
                new string[2] {"Wahl-Coates School", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/20"},
                new string[2] {"O'Neal Foundation", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/21"},
                new string[2] {"Southern Railway Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/22"},
                new string[2] {"Bellair Plantation", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/23"},
                new string[2] {"George B. Singletary Chapter U.D.C.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/24"},
                new string[2] {"Littleton College Memorial Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/25"},
                new string[2] {"Halifax County Historical Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/26"},
                new string[2] {"Delta Kappa Gamma Society International, Beta Alpha and Delta Chapters", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/27"},
                new string[2] {"Alvan Drew School", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/28"},
                new string[2] {"Halifax School", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/29"},
                new string[2] {"American Legion", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/30"},
                new string[2] {"C. H. Fowler and Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/31"},
                new string[2] {"W. J. Swan Store", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/32"},
                new string[2] {"Pitt County Bar Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/33"},
                new string[2] {"End of the Century Book Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/34"},
                new string[2] {"Massachusetts Volunteer Militia", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/35"},
                new string[2] {"Pamlico Lumber Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/36"},
                new string[2] {"Export Leaf Tobacco Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/37"},
                new string[2] {"Imperial Tobacco Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/38"},
                new string[2] {"Growers Cooperative Warehouse, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/39"},
                new string[2] {"North Carolina Academy of Science", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/40"},
                new string[2] {"New Bern Historical Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/41"},
                new string[2] {"Association of Historians in Eastern North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/42"},
                new string[2] {"American Association of University Professors, ECU Chapter", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/43"},
                new string[2] {"Pitt County Historical Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/44"},
                new string[2] {"Perquimans County Historical Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/45"},
                new string[2] {"Pitt County Democratic Executive Committee", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/47"},
                new string[2] {"New Bern Chamber of Commerce", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/48"},
                new string[2] {"North Carolina-Virginia College English Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/49"},
                new string[2] {"Eastern North Carolina Section of the American Chemical Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/50"},
                new string[2] {"Hearts Ease Grange Chapter", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/51"},
                new string[2] {"Chatham Book Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/52"},
                new string[2] {"Ku Klux Klan (1915-)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/53"},
                new string[2] {"Hyde County Historical Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/54"},
                new string[2] {"Sans Souci Book Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/55"},
                new string[2] {"King's Daughters and Sons", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/56"},
                new string[2] {"Elizabeth City Iron Works & Supply Co.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/57"},
                new string[2] {"Second Judicial District of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/58"},
                new string[2] {"South Atlantic Philosophy of Education Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/59"},
                new string[2] {"S. R. Fowle & Son Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/60"},
                new string[2] {"F. Rhem and Sons Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/61"},
                new string[2] {"East Indiaman", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/62"},
                new string[2] {"Neuse Forest Junior College", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/63"},
                new string[2] {"Star Brick Warehouse", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/64"},
                new string[2] {"F.S. Royster Mercantile Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/65"},
                new string[2] {"Coastal Plains Fair Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/66"},
                new string[2] {"Tarboro Temperance Society (Tarboro, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/67"},
                new string[2] {"Bank of Hobbsville (Hobbsville, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/68"},
                new string[2] {"Independent Order of Odd Fellows. Edgecombe Lodge no. 50 (Tarboro, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/69"},
                new string[2] {"Cozart, Eagles, and Carr Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/70"},
                new string[2] {"United States. Coast Guard Auxiliary", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/71"},
                new string[2] {"Old Sparta Farmers' Alliance", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/72"},
                new string[2] {"Little Rock Dairy Farm", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/73"},
                new string[2] {"Tar River Oil Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/74"},
                new string[2] {"Greenville Area Preservation Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/75"},
                new string[2] {"Grifton Hotel", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/76"},
                new string[2] {"United States. Navy Department", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/77"},
                new string[2] {"United States Naval Academy. Class of 1941", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/78"},
                new string[2] {"Beaufort County Schools (Beaufort County, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/79"},
                new string[2] {"U.S. Navy Memorial Foundation", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/80"},
                new string[2] {"Stone Towing Line", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/81"},
                new string[2] {"North American Society for Oceanic History", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/82"},
                new string[2] {"Murfreesboro Historical Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/83"},
                new string[2] {"Cape Lookout Yacht Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/84"},
                new string[2] {"St. Barnabas Episcopal Church (Snow Hill, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/85"},
                new string[2] {"St. Thomas' Episcopal Church (Windsor, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/86"},
                new string[2] {"St. James African Methodist Episcopal Zion Church (Snow Hill, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/87"},
                new string[2] {"Hagerty Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/88"},
                new string[2] {"Universalist Church (Woodington, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/89"},
                new string[2] {"Lenoir County Colonial Commission", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/90"},
                new string[2] {"Eric G. Flannagan & Sons Architects and Engingeers (Henderson, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/91"},
                new string[2] {"R.C. Chadwick Company (Swan Quarter, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/92"},
                new string[2] {"Universal Leaf Tobacco Company (Richmond, VA)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/93"},
                new string[2] {"League of Women Voters (Pitt County, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/94"},
                new string[2] {"Holbrook Microfilming Services (New York, N.Y.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/95"},
                new string[2] {"U.S. Army Air Corps (Washington, D.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/96"},
                new string[2] {"Roanoke Island Baptist Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/97"},
                new string[2] {"Warren Plains Baptist Church (Warrenton, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/98"},
                new string[2] {"Eden Methodist Church (Enfield, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/99"},
                new string[2] {"Whitaker's Chapel", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/100"},
                new string[2] {"Greenville Chamber of Commerce (Greenville, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/101"},
                new string[2] {"A. Hoen & Co.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/102"},
                new string[2] {"American Battle Monuments Commission", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/103"},
                new string[2] {"North Carolina Conference Historical Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/104"},
                new string[2] {"Skewarkey Union Meeting", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/105"},
                new string[2] {"Winterville Baptist Church (Winterville, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/106"},
                new string[2] {"United States. Army. Colored Infantry Regiment, 37th (1864-1867)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/107"},
                new string[2] {"U.S. Naval Institute", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/108"},
                new string[2] {"United States Navy B-1 Band", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/109"},
                new string[2] {"Tobacco History Symposium", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/110"},
                new string[2] {"L & T Respess Books", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/111"},
                new string[2] {"City of Greenville, NC Police Department", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/112"},
                new string[2] {"Great Swamp Primitive Baptist Church, Pitt County, North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/113"},
                new string[2] {"Ten Pound Island Book Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/114"},
                new string[2] {"King David Lodge No. 24 (Prince Hall) Ancient Free and Accepted Masons, Kinston, North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/115"},
                new string[2] {"Charles Apfelbaum, Rare Manuscripts & Archives", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/116"},
                new string[2] {"United States Coast Guard", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/117"},
                new string[2] {"Greenville High School, Greenville, NC", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/118"},
                new string[2] {"Friends of Joyner Library, East Carolina University, Greenville, NC", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/119"},
                new string[2] {"Maggs Bros. Ltd.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/120"},
                new string[2] {"Cowan's Auctions, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/121"},
                new string[2] {"Minges Bottling Group, Inc", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/122"},
                new string[2] {"Murfreesboro Historical Association, Murfreesboro, North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/123"},
                new string[2] {"Lenoir County Historical Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/124"},
                new string[2] {"Boy Scouts of America, East Carolina Council", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/125"},
                new string[2] {"Chapel Hill Rare Books", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/126"},
                new string[2] {"Agricultural Resources Center", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/127"},
                new string[2] {"Ellinwood Design Associates, Ltd.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/128"},
                new string[2] {"Between The Covers--Rare Books, Inc", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/129"},
                new string[2] {"W.W. Wooten Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/130"},
                new string[2] {"Edwards and Palmer Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/131"},
                new string[2] {"Barry Lawrence Ruderman Antique Maps, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/132"},
                new string[2] {"Democratic Women of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/133"},
                new string[2] {"Atlantic and North Carolina Railroad Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/134"},
                new string[2] {"Harper's Weekly", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/135"},
                new string[2] {"Broadfoot Publishing Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/136"},
                new string[2] {"Old Sparta Historical Preservation Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/137"},
                new string[2] {"Greenville Industries, Inc", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/138"},
                new string[2] {"Denning House Antiquarian Books & Manuscripts     ", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/139"},
                new string[2] {"Conoho Primitive Baptist Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/140"},
                new string[2] {"Pickwick Book Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/141"},
                new string[2] {"Playwrights Fund of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/142"},
                new string[2] {"August von Goethe Literaturverlag", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/143"},
                new string[2] {"Immanuel Baptist Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/145"},
                new string[2] {"Sons of the Revolution in the State of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/146"},
                new string[2] {"Rubenstein, David M., Rare Book & Manuscript Library", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/147"},
                new string[2] {"Concord Primitive Baptist Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/148"},
                new string[2] {"St. James Episcopal Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/149"},
                new string[2] {"Episcopal Diocese of East Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/150"},
                new string[2] {"East Carolina University. Institute of Outdoor Theatre", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/151"},
                new string[2] {"Dobbin Lodge, No. 13, Knights of Pythias", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/152"},
                new string[2] {"Michael Brown Rare Books, LLC", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/153"},
                new string[2] {"Bowen & Co. Lithographers", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/154"},
                new string[2] {"Renfrew Printing Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/155"},
                new string[2] {"Friends of Portsmouth Island", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/156"},
                new string[2] {"Inter Se Book Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/157"},
                new string[2] {"Greenville-Pitt County Chamber of Commerce, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/158"},
                new string[2] {"Phoenix Society for African American Research, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/159"},
                new string[2] {"Swiss Bear Downtown Development Corporation", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/160"},
                new string[2] {"Service League of Greenville", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/161"},
                new string[2] {"U.S. Navy B-1 Band", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/162"},
                new string[2] {"Sierra Club, Greenville, N.C., Chapter (Cypress Group)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/166"},
                new string[2] {"Dilettante Book Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/169"},
                new string[2] {"Seth Kaller, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/170"},
                new string[2] {"Cigaretten-Bilderdienst, G.m.b.H.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/171"},
                new string[2] {"The Country Doctor Museum", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/173"},
                new string[2] {"Beavans Drugstore", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/174"},
                new string[2] {"Memorial Hospital, Rocky Mount, North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/175"},
                new string[2] {"Nowell's Drug Store", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/176"},
                new string[2] {"Rocky Mount Sanitarium Nurses Alumnae", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/177"},
                new string[2] {"University of Pennsylvania. School of Medicine", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/178"},
                new string[2] {"William E. Laupus Health Sciences Library", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/179"},
                new string[2] {"East Carolina University. Medical Center News and Information", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/180"},
                new string[2] {"Pitt County Memorial Hospital", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/181"},
                new string[2] {"East Carolina University. School of Medicine", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/182"},
                new string[2] {"Medical Society of the State of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/183"},
                new string[2] {"North Carolina Surgical Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/184"},
                new string[2] {"U.S. Bankruptcy Court for the Eastern District of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/185"},
                new string[2] {"Red Banks Primitive Baptist Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/186"},
                new string[2] {"Watts Hospital School of Nursing", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/187"},
                new string[2] {"North Carolina Public Health Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/188"},
                new string[2] {"Daughters of the American Revolution, Betsy Dowdy Chapter", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/189"},
                new string[2] {"A.C. Monk & Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/190"},
                new string[2] {"Lynndale Garden Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/191"},
                new string[2] {"Parke, Davis & Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/192"},
                new string[2] {"Palaemon Press, Limited", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/193"},
                new string[2] {"Society for the Diffusion of Useful Knowledge", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/194"},
                new string[2] {"Lillabulero Press, Limited. Chapel Hill, NC. Northwood Narrows, NH", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/195"},
                new string[2] {"National Maritime Alliance", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/197"},
                new string[2] {"William Reese Company", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/198"},
                new string[2] {"Housing Authority of the City of Greenville", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/199"},
                new string[2] {"Greenville Tobacco Company, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/200"},
                new string[2] {"Cass Avenue Methodist Episcopal Church of Detroit", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/201"},
                new string[2] {"Perry-Weston Educational and Cultural Institute, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/202"},
                new string[2] {"City of Greenville (NC) Public Works Office", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/203"},
                new string[2] {"Harnett County (N.C.) Common Schools", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/204"},
                new string[2] {"Richland County, South Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/205"},
                new string[2] {"United States Postal Service", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/206"},
                new string[2] {"Jamestown Amusement & Vending Co., Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/207"},
                new string[2] {"Battleground Antiques. Will Gorges", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/208"},
                new string[2] {"Planning and Community Development Department", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/209"},
                new string[2] {"Winterville Chamber of Commerce", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/210"},
                new string[2] {"Winterville Historical and Arts Society, Inc.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/211"},
                new string[2] {"St. Paul's Episcopal Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/212"},
                new string[2] {"J.H. Colton & Co.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/213"},
                new string[2] {"Pitt County, N.C., Schools", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/214"},
                new string[2] {"Pitt/Greenville Chapter of the ACLU of NC", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/215"},
                new string[2] {"Historical Collectible Auction", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/216"},
                new string[2] {"Order of First Families of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/217"},
                new string[2] {"James W. Griffith, Jr., Architects", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/218"},
                new string[2] {"Kambini Mission, Mozambique", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/219"},
                new string[2] {"Buckingham Books", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/220"},
                new string[2] {"Dorothea Dix Hospital", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/221"},
                new string[2] {"Sanborn Map & Publishing Co.", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/222"},
                new string[2] {"Pitt County Planning Department", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/223"},
                new string[2] {"NCEast Alliance", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/224"},
                new string[2] {"Daily Reflector Newspaper", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/225"},
                new string[2] {"North Carolina State Highway and Public Works Commission", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/226"},
                new string[2] {"Sierra Club, North Carolina Chapter", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/227"},
                new string[2] {"Southern Genealogist's Exchange Society", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/228"},
                new string[2] {"Pipkin Family Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/229"},
                new string[2] {"Scottish Rite, Southern Jurisdiction, Prince Hall Affiliation", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/230"},
                new string[2] {"East Carolina Native American Organization", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/231"},
                new string[2] {"Z. Smith Reynolds Library. Special Collections & Archives", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/232"},
                new string[2] {"Disciples of Christ Congo Mission (DCCM)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/233"},
                new string[2] {"Reelife Motion Pictures", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/234"},
                new string[2] {"East Carolina University. Army ROTC program", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/235"},
                new string[2] {"Kappa Alpha Order", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/237"},
                new string[2] {"Young Women's Christian Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/238"},
                new string[2] {"Tavistock Books", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/240"},
                new string[2] {"United States Army. First North Carolina Volunteers", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/241"},
                new string[2] {"Doane Herring", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/242"},
                new string[2] {"W.S. Anderson's Drug Store", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/243"},
                new string[2] {"A.W. Rowland", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/244"},
                new string[2] {"E.M. Nadal", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/245"},
                new string[2] {"E.L. Laurent", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/246"},
                new string[2] {"East Carolina University. College of Nursing", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/247"},
                new string[2] {"Imperial Tobacco Company of Great Britain and Ireland", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/248"},
                new string[2] {"Goldsboro High School (Goldsboro, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/249"},
                new string[2] {"London American Newspaper", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/250"},
                new string[2] {"U.S.S. Emmons Association", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/251"},
                new string[2] {"Queens Borough Public Library. Long Island Division", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/252"},
                new string[2] {"Sheppard Memorial Library", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/253"},
                new string[2] {"Greenville Garden Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/254"},
                new string[2] {"Black Jack Free Will Baptist Church", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/255"},
                new string[2] {"Clio Book Club", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/256"},
                new string[2] {"Redevelopment Commission of the City of Greenville (Greenville, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/257"},
                new string[2] {"Huguenot Society of North Carolina", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/258"},
                new string[2] {"WVOT (Radio station : Wilson, Wilson County, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/259"},
                new string[2] {"Kinghts of Pythias. Salisbury-Rowan Lodge No. 100 (Salisbury, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/260"},
                new string[2] {"Knights of Pythias. Cumberland Lodge No. 5 (Fayetteville, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/261"},
                new string[2] {"Rotary Club (Greenville, N.C.)", "http://archivesspace.ecu.edu/agents/agent_corporate_entity/262"}

            };
            Relations = new List<string[]>
            {
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/4", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1588"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/7", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1727"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/7", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2628"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/7", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2629"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/8", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1161"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/9", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1187"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/10", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1203"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/11", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1239"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/12", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1252"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/13", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1315"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/14", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1369"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/15", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1394"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/16", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1324"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/16", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1395"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/17", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1432"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/18", "personalNameCreator", "http://archivesspace.ecu.edu/resources/341"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/19", "personalNameCreator", "http://archivesspace.ecu.edu/resources/342"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/20", "personalNameCreator", "http://archivesspace.ecu.edu/resources/343"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/21", "personalNameCreator", "http://archivesspace.ecu.edu/resources/357"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/22", "personalNameCreator", "http://archivesspace.ecu.edu/resources/365"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/23", "personalNameCreator", "http://archivesspace.ecu.edu/resources/424"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/24", "personalNameCreator", "http://archivesspace.ecu.edu/resources/444"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/25", "personalNameCreator", "http://archivesspace.ecu.edu/resources/450"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/26", "personalNameCreator", "http://archivesspace.ecu.edu/resources/451"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/27", "personalNameCreator", "http://archivesspace.ecu.edu/resources/453"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/27", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2136"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/28", "personalNameCreator", "http://archivesspace.ecu.edu/resources/454"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/29", "personalNameCreator", "http://archivesspace.ecu.edu/resources/455"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/30", "personalNameCreator", "http://archivesspace.ecu.edu/resources/456"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/31", "personalNameCreator", "http://archivesspace.ecu.edu/resources/458"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/32", "personalNameCreator", "http://archivesspace.ecu.edu/resources/458"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/33", "personalNameCreator", "http://archivesspace.ecu.edu/resources/460"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/34", "personalNameCreator", "http://archivesspace.ecu.edu/resources/486"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/35", "personalNameCreator", "http://archivesspace.ecu.edu/resources/501"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/36", "personalNameCreator", "http://archivesspace.ecu.edu/resources/504"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/37", "personalNameCreator", "http://archivesspace.ecu.edu/resources/590"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/38", "personalNameCreator", "http://archivesspace.ecu.edu/resources/596"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/39", "personalNameCreator", "http://archivesspace.ecu.edu/resources/603"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/40", "personalNameCreator", "http://archivesspace.ecu.edu/resources/619"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/41", "personalNameCreator", "http://archivesspace.ecu.edu/resources/620"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/42", "personalNameCreator", "http://archivesspace.ecu.edu/resources/621"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/43", "personalNameCreator", "http://archivesspace.ecu.edu/resources/628"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/44", "personalNameCreator", "http://archivesspace.ecu.edu/resources/631"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/45", "personalNameCreator", "http://archivesspace.ecu.edu/resources/636"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/47", "personalNameCreator", "http://archivesspace.ecu.edu/resources/685"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/48", "personalNameCreator", "http://archivesspace.ecu.edu/resources/691"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/49", "personalNameCreator", "http://archivesspace.ecu.edu/resources/692"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/50", "personalNameCreator", "http://archivesspace.ecu.edu/resources/737"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/51", "personalNameCreator", "http://archivesspace.ecu.edu/resources/743"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/52", "personalNameCreator", "http://archivesspace.ecu.edu/resources/746"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/53", "personalNameCreator", "http://archivesspace.ecu.edu/resources/762"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/54", "personalNameCreator", "http://archivesspace.ecu.edu/resources/770"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/55", "personalNameCreator", "http://archivesspace.ecu.edu/resources/773"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/56", "personalNameCreator", "http://archivesspace.ecu.edu/resources/780"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/57", "personalNameCreator", "http://archivesspace.ecu.edu/resources/781"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/58", "personalNameCreator", "http://archivesspace.ecu.edu/resources/782"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/59", "personalNameCreator", "http://archivesspace.ecu.edu/resources/788"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/60", "personalNameCreator", "http://archivesspace.ecu.edu/resources/797"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/61", "personalNameCreator", "http://archivesspace.ecu.edu/resources/806"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/62", "personalNameCreator", "http://archivesspace.ecu.edu/resources/811"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/63", "personalNameCreator", "http://archivesspace.ecu.edu/resources/828"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/64", "personalNameCreator", "http://archivesspace.ecu.edu/resources/846"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/65", "personalNameCreator", "http://archivesspace.ecu.edu/resources/849"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/66", "personalNameCreator", "http://archivesspace.ecu.edu/resources/850"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/67", "personalNameCreator", "http://archivesspace.ecu.edu/resources/868"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/68", "personalNameCreator", "http://archivesspace.ecu.edu/resources/869"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/69", "personalNameCreator", "http://archivesspace.ecu.edu/resources/871"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/70", "personalNameCreator", "http://archivesspace.ecu.edu/resources/886"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/71", "personalNameCreator", "http://archivesspace.ecu.edu/resources/901"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/72", "personalNameCreator", "http://archivesspace.ecu.edu/resources/902"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/73", "personalNameCreator", "http://archivesspace.ecu.edu/resources/905"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/74", "personalNameCreator", "http://archivesspace.ecu.edu/resources/961"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/75", "personalNameSource", "http://archivesspace.ecu.edu/resources/963"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/75", "personalNameCreator", "http://archivesspace.ecu.edu/resources/963"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/76", "personalNameCreator", "http://archivesspace.ecu.edu/resources/991"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/77", "personalNameCreator", "http://archivesspace.ecu.edu/resources/995"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/78", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1002"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/79", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1008"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/80", "personalNameSource", "http://archivesspace.ecu.edu/resources/1082"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/80", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1092"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/80", "personalNameSource", "http://archivesspace.ecu.edu/resources/1110"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/81", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1119"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/82", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1129"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/83", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1131"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/83", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1132"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/83", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1133"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/83", "personalNameSource", "http://archivesspace.ecu.edu/resources/1134"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/83", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1135"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/84", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1455"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/85", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1469"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/86", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1482"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/87", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1521"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/88", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1527"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/89", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1547"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/90", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1564"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/91", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1591"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/92", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1593"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/93", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1595"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/94", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1600"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/95", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1117"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/96", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1117"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/97", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1572"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/98", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1898"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/99", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1899"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/100", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1900"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/101", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1966"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/102", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1967"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/103", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1968"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/104", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2014"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/105", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2021"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/106", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2026"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/107", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2031"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/108", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2280"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/109", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2427"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/110", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2152"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/111", "personalNameSource", "http://archivesspace.ecu.edu/resources/1451"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/112", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1519"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/113", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1301"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1462"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1506"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1507"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1566"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1718"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1756"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1843"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/114", "personalNameSource", "http://archivesspace.ecu.edu/resources/1893"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/115", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1410"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/116", "personalNameSource", "http://archivesspace.ecu.edu/resources/1470"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/116", "personalNameSource", "http://archivesspace.ecu.edu/resources/1501"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/117", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1465"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/118", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1232"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/119", "personalNameSource", "http://archivesspace.ecu.edu/resources/1182"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/120", "personalNameSource", "http://archivesspace.ecu.edu/resources/1597"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/120", "personalNameSource", "http://archivesspace.ecu.edu/resources/1598"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/121", "personalNameSource", "http://archivesspace.ecu.edu/resources/1736"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/122", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1579"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/123", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1136"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/124", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1737"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/125", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1747"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/126", "personalNameSource", "http://archivesspace.ecu.edu/resources/1542"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/127", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1349"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/128", "personalNameSource", "http://archivesspace.ecu.edu/resources/1248"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/128", "personalNameSource", "http://archivesspace.ecu.edu/resources/1249"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1748"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1757"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1786"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1789"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1810"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1815"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1839"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1842"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1849"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1850"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1851"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1852"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1853"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/129", "personalNameSource", "http://archivesspace.ecu.edu/resources/1864"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/130", "personalNameCreator", "http://archivesspace.ecu.edu/resources/843"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/131", "personalNameCreator", "http://archivesspace.ecu.edu/resources/851"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1980"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1981"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1982"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1983"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1984"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1985"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1986"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1987"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1988"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1989"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1990"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/132", "personalNameSource", "http://archivesspace.ecu.edu/resources/1991"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/133", "personalNameCreator", "http://archivesspace.ecu.edu/resources/860"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/134", "personalNameCreator", "http://archivesspace.ecu.edu/resources/847"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/135", "personalNameCreator", "http://archivesspace.ecu.edu/resources/847"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/136", "personalNameSource", "http://archivesspace.ecu.edu/resources/1828"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/136", "personalNameSource", "http://archivesspace.ecu.edu/resources/1829"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/137", "personalNameSource", "http://archivesspace.ecu.edu/resources/1766"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/138", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1755"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1769"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1771"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1784"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1785"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1809"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1812"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1812"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1822"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1847"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1854"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1855"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1878"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/139", "personalNameSource", "http://archivesspace.ecu.edu/resources/1886"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/140", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1770"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/141", "personalNameCreator", "http://archivesspace.ecu.edu/resources/925"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/142", "personalNameCreator", "http://archivesspace.ecu.edu/resources/928"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/143", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1444"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/145", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1758"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/146", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1160"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/147", "personalNameSource", "http://archivesspace.ecu.edu/resources/1626"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/148", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1777"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/149", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1242"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/150", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1242"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/150", "personalNameSource", "http://archivesspace.ecu.edu/resources/1242"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/151", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1797"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/152", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1796"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/153", "personalNameSource", "http://archivesspace.ecu.edu/resources/1804"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/154", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1987"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/155", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1795"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/156", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1802"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/157", "personalNameSource", "http://archivesspace.ecu.edu/resources/1813"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/157", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1813"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/158", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1806"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/159", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1807"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/160", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1800"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/160", "personalNameSource", "http://archivesspace.ecu.edu/resources/1800"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/161", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1790"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/161", "personalNameSource", "http://archivesspace.ecu.edu/resources/1790"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/162", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1415"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/166", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1787"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/169", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1819"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/170", "personalNameSource", "http://archivesspace.ecu.edu/resources/1818"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/170", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1818"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/171", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1817"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2486"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2493"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2517"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2521"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2532"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2550"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2556"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2577"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2581"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/173", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2582"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/174", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2489"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/175", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2546"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/176", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2549"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/177", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2563"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/178", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2592"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2600"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2609"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2610"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2612"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2617"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2618"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2621"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2624"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2625"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2627"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2631"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2632"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2638"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2640"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2641"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2643"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2646"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2647"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2651"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/179", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2653"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/180", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2604"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/181", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2606"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/182", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2608"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/183", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2626"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/184", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2644"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/185", "personalNameSource", "http://archivesspace.ecu.edu/resources/1517"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/186", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1820"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/187", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2498"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/188", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2657"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/189", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1826"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/190", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1832"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/191", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1825"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/192", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2658"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/193", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1642"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/194", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1991"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/195", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1699"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/197", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1840"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/198", "personalNameSource", "http://archivesspace.ecu.edu/resources/1859"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/199", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1367"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/200", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1856"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/201", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1854"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/202", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1846"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/203", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1397"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/204", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1426"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/205", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1389"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/206", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1358"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/207", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1405"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/208", "personalNameSource", "http://archivesspace.ecu.edu/resources/660"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/208", "personalNameSource", "http://archivesspace.ecu.edu/resources/1870"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/209", "personalNameSource", "http://archivesspace.ecu.edu/resources/1032"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/210", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1860"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/211", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1860"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/212", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1901"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/212", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2035"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/212", "personalNameSource", "http://archivesspace.ecu.edu/resources/2035"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/213", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1954"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/213", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1957"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/214", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1153"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/214", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1869"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/215", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1837"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/216", "personalNameSource", "http://archivesspace.ecu.edu/resources/1317"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/217", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1866"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/218", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1248"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/219", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1878"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/220", "personalNameSource", "http://archivesspace.ecu.edu/resources/1876"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/221", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1875"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/222", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1938"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/223", "personalNameSource", "http://archivesspace.ecu.edu/resources/1879"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/224", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1877"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/225", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1474"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/226", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1198"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/227", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1221"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/228", "personalNameSource", "http://archivesspace.ecu.edu/resources/1373"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/229", "personalNameSource", "http://archivesspace.ecu.edu/resources/1373"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/230", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1870"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/231", "personalNameCreator", "http://archivesspace.ecu.edu/resources/181"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/232", "personalNameSource", "http://archivesspace.ecu.edu/resources/1650"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/233", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1886"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/234", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1314"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/235", "personalNameCreator", "http://archivesspace.ecu.edu/resources/116"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/237", "personalNameCreator", "http://archivesspace.ecu.edu/resources/186"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/238", "personalNameCreator", "http://archivesspace.ecu.edu/resources/176"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/240", "personalNameSource", "http://archivesspace.ecu.edu/resources/1888"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/241", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1888"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/242", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2596"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/243", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2596"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/244", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2596"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/245", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2596"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/246", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2596"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/247", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2662"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/248", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1253"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/249", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1321"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/250", "personalNameCreator", "http://archivesspace.ecu.edu/resources/2128"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/251", "personalNameSource", "http://archivesspace.ecu.edu/resources/1227"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/251", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1331"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/251", "personalNameSource", "http://archivesspace.ecu.edu/resources/1331"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/252", "personalNameSource", "http://archivesspace.ecu.edu/resources/1477"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/253", "personalNameSource", "http://archivesspace.ecu.edu/resources/1189"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/254", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1189"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/255", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1896"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/256", "personalNameCreator", "http://archivesspace.ecu.edu/resources/937"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/257", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1032"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/258", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1454"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/259", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1725"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/260", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1724"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/261", "personalNameCreator", "http://archivesspace.ecu.edu/resources/1592"},
                new string[3] {"http://archivesspace.ecu.edu/agents/agent_corporate_entity/262", "personalNameCreator", "http://archivesspace.ecu.edu/resources/671"}

            };
        }
    }
}